apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandelbrot-web
  labels:
    app: mandelbrot-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mandelbrot-web
  template:
    metadata:
      labels:
        app: mandelbrot-web
    spec:
      containers:
      - name: mandelbrot-web
        image: gcr.io/knative-istio-riff/mandelbrot-web:0.0.6-SNAPSHOT
        ports:
        - containerPort: 8080