---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "mandelbrot-web-service"
  namespace: "default"
  labels:
    app: "mandelbrot-web"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "mandelbrot-web"
  type: "LoadBalancer"
  loadBalancerIP: ""